# Generated by Django 2.0.5 on 2018-05-09 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='unidade',
            field=models.CharField(default='un', max_length=5),
            preserve_default=False,
        ),
    ]
